language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t dev4venkat/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dev4venkat/react-test npm test

after_success:
    - docker build -t dev4venkat/multi-client ./client
    - docker build -t dev4venkat/multi-ngnix ./ngnix
    - docker build -t dev4venkat/multi-server ./server  
    - docker build -t dev4venkat/multi-worker ./worker
    
    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

    # Take images and push them to docker hub
    - docker push dev4venkat/multi-client
    - docker push dev4venkat/multi-ngnix
    - docker push ev4venkat/multi-server
    - docker push ev4venkat/multi-worker

